In [4]:
!pip install numpy

## 点云可视化

In [42]:
# pointcloud_visualize 1 pcd

import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("./res/data/fragment.pcd")
print(pcd)
print(np.asarray(pcd.points))
#显示点云数据
o3d.visualization.draw_geometries([pcd],
                               zoom=0.3412,
                               front=[0.4257, -0.2125, -0.8795],
                               lookat=[2.6172, 2.0475, 1.532],
                               up=[-0.0694, -0.9768, 0.2024])

PointCloud with 113662 points.
[[1.16796875 1.01803279 0.96484375]
 [1.16845131 1.01953125 0.96484375]
 [1.16796875 1.02158833 0.96484375]
 ...
 [2.19495988 2.62890625 1.45703125]
 [2.19140625 2.63435388 1.45703125]
 [2.19140625 2.62890625 1.45781052]]


In [26]:
#pointcloud_visualize 2 pcd

import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("./res/data/fragment.pcd", format='auto', remove_nan_points=True, remove_infinite_points=True, print_progress=True)
print(pcd) # 输出点云点的个数
print(np.asarray(pcd.points)) # 输出点的三维坐标
# pcd.paint_uniform_color([1, 0, 0])
# pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1, (1, 3)))
o3d.io.write_point_cloud("./res/data/copy_of_fragment.pcd", pcd)
o3d.visualization.draw_geometries([pcd], window_name='Open3D', width=1920, height=1080, left=50, top=50, point_show_normal=False, mesh_show_wireframe=False, mesh_show_back_face=False)

PointCloud with 113662 points.
[[1.16796875 1.01803279 0.96484375]
 [1.16845131 1.01953125 0.96484375]
 [1.16796875 1.02158833 0.96484375]
 ...
 [2.19495988 2.62890625 1.45703125]
 [2.19140625 2.63435388 1.45703125]
 [2.19140625 2.62890625 1.45781052]]


## Color

In [27]:
# 随机上色
# pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1, (1, 3)))

# 指定颜色
# pcd.paint_uniform_color([1, 0, 0])

## 读取三维模型并转换成点云(stl/ply/obj/off/gltf/glb)

In [41]:
# model visualize
path_obj = './res/data/chair_0001.off'

mesh = o3d.io.read_triangle_mesh(path_obj)

mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh])

In [39]:
# model -> pointcloud

# 均匀采样5000个点
pcd = mesh.sample_points_uniformly(number_of_points=5000)

o3d.visualization.draw_geometries([pcd])

In [40]:
# poisson_disk 5000 points

pcd = mesh.sample_points_uniformly(number_of_points=5000)

o3d.visualization.draw_geometries([pcd])

poisson相比于均匀, 边缘点分布更加均匀